sudo: false
language: node_js
node_js: 14.15.3
script:
- npm run audit
- npm run snyk
- npm run lint
- npm run test
after_success: npm run coveralls
env:
  global:
    secure: QLEsYUkxSoNstoOmkTpw9mHWbxOoUyflxkiy2um7yH98TYWN3LnLfMWYdyGHrUQBwxnbp411TuvjAxYVD246ZCWHOoL+POswAlUVwT6wL7u6qkVI9dvtQ71Phv9QF9mbkxOUCGmnzQdJCQhxFsUQwx53X4OjFw8uv+Kdl0CJUDURLCp5xoQ5zfWK5+KXSBmOFuUovplghy5eRWeOhLxnY4SBHvn/ntYZWNNdWqboQPZjJsp30W0a91ZiV7PnFBwtK5mmcBPgRM1T549OTb4Zc6hgCXKzlse1jnpRqdHOt4hLFjMosYujg/LgkOlYYB8h9F9v5Lwi5tXwUEOQ5Kpd6UnlY0TZ7jg9vLJvcJNM9K22BXEvDcCBatgdtFZYXvqxt2aGLnAspX5k/hLaoelws6nlrVkrAC9MPpReNaQMVG03+G+KRAbyHirqncv36+fKHeC4BKcdF3J9mkk7xqW7C/0nBnvvsGfi6ZRBDq9XB1aouqEtqgcCer3A/4ZWK11FZPx//qrXMQHtN2d52Lys+77Bjs4WO0C7TMY1a119xDokJUkhKupLPtw8wSYzSmg5Ldbc78pGEOmEhDIP1cdz5JvfyM5Spa7p38L3YmAxV4V2pk93fHz3yXy4KMfeejBJOLWnG+qsZ/SPAW/meJpIYFDIwXv5h7kp9m7FQ9KyJ1o=
deploy:
  provider: npm
  email: adonisv79@gmail.com
  api_key:
    secure: An0qsGIlg6vJb/CEIoH+GOqFaS9omSwRqHP7xU4nlPkoAyYibavv85pJBp5ZBzxoB6o7pFuZBgQMvEnsuqf97OBsdxgfHBiggDILrHfoqWS/GYy4GsYDQhgVfk/gMzqTKicW1X3ao4/0cujMv2Nm2dVJzUV1mbCrgNPqcv/H1/AxGZBPPmbVEHpkvsAY3jZFyVAb97JqSmQqvyyfAiG26CAJrDgFpDIFS+8gMcXyyHGXDsOiqI5Drly+IHlHB1wW2p/NZ+GB13yJQXpQyoXj9eAhR+9X2AwgXTE04rogqYUYq0RDz0JKVpuys2rpT5t2BTNNbkW8bNefwLdXYZr18jdp7G2j15RezmTF9XMsOPQJl0MAHCPZ8td810E96T0uchQ/2vCHkPiddII5+oCX0hNXxGS3HfuIqqkF9RL3XfJsZJJ6Bmvb13CIqk6yzFbU34OTjAlEZAIxeRFl41CbYkMx0DwAYW6reqlcpt+XQpTjuPv/NfIM+JI0EYICOOfVaZKfP4K6+qNsVoZJU6QOE8MVj9MW634EqazUyRl6VNXmZPxNBdhlwXK9b8Gn32U/QteCiZeoh9721JSGIALeSS0GifaDdOypaT6SWfnZZunHSRbVlJyAtJX0Uy7jLU90p7L4UxkJQbAO2A5mNxO4dyn5lStDJOQszjs+tL7kiVg=
  on:
    tags: true
    branch: master